apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: obo-prometheus-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: obo-prometheus-operator
    app.kubernetes.io/part-of: obo-prometheus-operator
  name: obo-prometheus-operatorpwtb
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: obo-prometheus-operator
    weight: 100
status: {}
